import 'dart:io' show Platform;

import 'package:apprefer/apprefer.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:gleap_sdk/gleap_sdk.dart' hide LogLevel;
import 'package:purchases_flutter/purchases_flutter.dart';

import 'env.dart';

/// Boots every third-party service Chaos depends on.
///
/// Each service is wrapped in its own try/catch so that a single misconfigured
/// dependency does not prevent the app from booting. Missing Stage 2 artefacts
/// (for example, `firebase_options.dart` before `flutterfire configure` has
/// been run, or `--dart-define` keys in local builds) are treated as warnings,
/// not fatal errors.
///
/// Call from `main()` before `runApp`.
Future<void> bootServices() async {
  await _initFirebase();
  await _initCrashlytics();
  await _initAppRefer();
  await _initRevenueCat();
  _initGleap();
}

Future<void> _initFirebase() async {
  try {
    // `firebase_options.dart` is generated by `flutterfire configure`.
    // Until Stage 2 dashboard work is done we rely on the native
    // `google-services.json` / `GoogleService-Info.plist` if present.
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp();
    }
    debugPrint('[Chaos] Firebase initialised');
  } catch (e) {
    debugPrint(
      '[Chaos] Firebase init skipped — configure via flutterfire '
      'configure to enable. Error: $e',
    );
  }
}

Future<void> _initCrashlytics() async {
  if (kIsWeb) return;
  try {
    final crashlytics = FirebaseCrashlytics.instance;
    await crashlytics.setCrashlyticsCollectionEnabled(!kDebugMode);
    FlutterError.onError = crashlytics.recordFlutterFatalError;
    PlatformDispatcher.instance.onError = (error, stack) {
      crashlytics.recordError(error, stack, fatal: true);
      return true;
    };
    debugPrint('[Chaos] Crashlytics wired');
  } catch (e) {
    debugPrint('[Chaos] Crashlytics init skipped: $e');
  }
}

Future<void> _initAppRefer() async {
  if (!Env.hasAppRefer) {
    debugPrint('[Chaos] AppRefer skipped — no APPREFER_KEY');
    return;
  }
  try {
    await AppReferSDK.configure(AppReferConfig(apiKey: Env.appReferKey));
    final deviceId = await AppReferSDK.getDeviceId();
    if (deviceId != null && Env.hasRevenueCat) {
      await Purchases.setAttributes({'appreferId': deviceId});
    }
    debugPrint('[Chaos] AppRefer configured');
  } catch (e) {
    debugPrint('[Chaos] AppRefer configure failed: $e');
  }
}

Future<void> _initRevenueCat() async {
  if (!Env.hasRevenueCat) {
    debugPrint('[Chaos] RevenueCat skipped — no REVENUECAT_* keys');
    return;
  }
  try {
    await Purchases.setLogLevel(LogLevel.warn);
    final key = Platform.isIOS ? Env.revenueCatIosKey : Env.revenueCatAndroidKey;
    if (key.isEmpty) {
      debugPrint('[Chaos] RevenueCat key missing for platform');
      return;
    }
    await Purchases.configure(PurchasesConfiguration(key));
    debugPrint('[Chaos] RevenueCat configured');
  } catch (e) {
    debugPrint('[Chaos] RevenueCat init failed: $e');
  }
}

void _initGleap() {
  if (!Env.hasGleap) {
    debugPrint('[Chaos] Gleap skipped — no GLEAP_SDK_KEY');
    return;
  }
  try {
    Gleap.initialize(token: Env.gleapSdkKey);
    debugPrint('[Chaos] Gleap initialised');
  } catch (e) {
    debugPrint('[Chaos] Gleap init failed: $e');
  }
}

/// Analytics wrapper — safe to call even when Firebase is not configured.
class ChaosAnalytics {
  ChaosAnalytics._();

  static FirebaseAnalytics? _instance() {
    try {
      if (Firebase.apps.isEmpty) return null;
      return FirebaseAnalytics.instance;
    } catch (_) {
      return null;
    }
  }

  static Future<void> log(String name, {Map<String, Object>? params}) async {
    final analytics = _instance();
    if (analytics == null) return;
    try {
      await analytics.logEvent(name: name, parameters: params);
    } catch (_) {
      // Non-fatal.
    }
  }
}
